name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    # Ensure this runs on x86 linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying to ${{ secrets.RUSTY_IP }}"
      - name: Test
        run: ping -c 1 ${{ secrets.RUSTY_IP }}
      - name: Test partial head reveal
        run: echo ${{ secrets.RUSTY_IP }} | head -c 3
      - name: Test partial tail reveal
        run: echo ${{ secrets.RUSTY_IP }} | tail -c 3