name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    # Ensure this runs on x86 linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup /etc/hosts
        run: |
            echo "${{ secrets.RUSTY_IP }} rusty" | sudo tee -a /etc/hosts
      - name: Test
        run: curl -i -v rusty